# Generated by Django 5.0.1 on 2024-02-01 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={},
        ),
    ]
