# Generated by Django 5.0.1 on 2024-02-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_alter_pais_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
    ]
