# Generated by Django 5.0.1 on 2024-02-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productsubcategory_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory_id',
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ManyToManyField(blank=True, null=True, to='product.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_id',
            field=models.ManyToManyField(blank=True, null=True, to='product.productsubcategory'),
        ),
    ]
