# Generated by Django 5.0.1 on 2024-02-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productsubcategory_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ManyToManyField(blank=True, limit_choices_to={'active': True}, to='product.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/static/products/img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory_id',
            field=models.ManyToManyField(blank=True, limit_choices_to={'active': True}, to='product.productsubcategory'),
        ),
    ]
