# Generated by Django 5.0.1 on 2024-02-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_size_remove_product_size_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.IntegerField(),
        ),
    ]
